# Generated by Django 6.0 on 2025-12-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='จำนวนครั้งที่ retry การส่ง notification ในรอบปัจจุบัน'),
        ),
    ]
