# Generated by Django 6.0 on 2025-12-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_notification_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_sent_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='last_sent_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
