# Generated by Django 6.0 on 2026-01-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_notification_last_sent_event_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('FO', 'Front Office'), ('RS', 'Reservations'), ('EO', 'Executive Office'), ('FI', 'Finance'), ('SM', 'Sales Marketing'), ('RV', 'Revenue'), ('FB', 'Food & Beverage'), ('KC', 'Kitchen'), ('EN', 'Engineering'), ('HR', 'Human Resource'), ('HK', 'House Keeping')], help_text='User Department', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='interval_unit',
            field=models.CharField(blank=True, choices=[('minute', 'minute'), ('hour', 'hour'), ('day', 'day'), ('month', 'month')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure')], default='pending', help_text='Notification Sending Status', max_length=10),
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
