# Generated by Django 6.0 on 2026-01-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_user_department_alter_notification_interval_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('UN', 'Unassigned (ต้องแก้ไข)'), ('FO', 'Front Office'), ('RS', 'Reservations'), ('EO', 'Executive Office'), ('FI', 'Finance'), ('SM', 'Sales Marketing'), ('RV', 'Revenue'), ('FB', 'Food & Beverage'), ('KC', 'Kitchen'), ('EN', 'Engineering'), ('HR', 'Human Resource'), ('HK', 'House Keeping')], default='UN', help_text='User Department', max_length=2),
            preserve_default=False,
        ),
    ]
